### ISSUE TITLE
Download Ontologia

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#208]
Il sistema restituisce un errore sia se si prova a fare il download dell'ontologia OWL full, sia se si prova a fare il download dell'ontologia approssimata.

Rispettivamente:

-------------------  E R R O R      S T A R T  -------------------------
org.semanticweb.owlapi.model.OWLOntologyAlreadyExistsException: Ontology already exists. OntologyID(OntologyIRI(<http://www.movieontology.org/ontology/>) VersionIRI(<null>))
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1027)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:967)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:983)
	at com.mwsx.engine.MwsxOntologyManager.getApproximatedOntologyVersionOwlFile(MwsxOntologyManager.java:3070)
	at com.mwsx.engine.MwsxOntologyManager.getApproximatedOntology(MwsxOntologyManager.java:3059)
	at com.mwsx.services.MwsxService.get__owlOntology_name_version(MwsxService.java:371)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

-----------------  E R R O R      S T A R T  -------------------------
org.semanticweb.HermiT.datatypes.UnsupportedDatatypeException: HermiT supports all and only the datatypes of the OWL 2 datatype map, see 
http://www.w3.org/TR/owl2-syntax/#Datatype_Maps. 
The datatype 'http://www.w3.org/2001/XMLSchema#date' is not part of the OWL 2 datatype map and 
no custom datatype definition is given; 
therefore, HermiT cannot handle this datatype.
	at org.semanticweb.HermiT.datatypes.DatatypeRegistry.getDatatypeHandlerFor(DatatypeRegistry.java:76)
	at org.semanticweb.HermiT.datatypes.DatatypeRegistry.getDatatypeHandlerFor(DatatypeRegistry.java:82)
	at org.semanticweb.HermiT.datatypes.DatatypeRegistry.validateDatatypeRestriction(DatatypeRegistry.java:113)
	at org.semanticweb.HermiT.structural.OWLClausification$DataRangeConverter.visit(OWLClausification.java:819)
	at uk.ac.manchester.cs.owl.owlapi.OWLDatatypeImpl.accept(OWLDatatypeImpl.java:267)
	at org.semanticweb.HermiT.structural.OWLClausification$DataRangeConverter.convertDataRange(OWLClausification.java:805)
	at org.semanticweb.HermiT.structural.OWLClausification$NormalizedAxiomClausifier.visit(OWLClausification.java:649)
	at uk.ac.manchester.cs.owl.owlapi.OWLDataAllValuesFromImpl.accept(OWLDataAllValuesFromImpl.java:82)
	at org.semanticweb.HermiT.structural.OWLClausification.clausify(OWLClausification.java:237)
	at org.semanticweb.HermiT.structural.OWLClausification.preprocessAndClausify(OWLClausification.java:167)
	at org.semanticweb.HermiT.Reasoner.loadOntology(Reasoner.java:208)
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:199)
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:173)

**Comment by roodsey** [comment]
Risolto il problema dello scaricamento che si verificava sempre al secondo tentativo di download per un bug di codice. L'errore di Hermit, viceversa, dipende dall'utilizzo di specifici tipi di dato non supportati da OWL2 (cosa chiaramente espressa nel messaggio d'errore tra l'altro). Occorre adeguare il file OWL di Books, oppure mettere mano all'approssimatore. Questa Issue è chiusa

**Comment by valeriosantarelli** [comment]
Riapro e me la assegno così verifico, c'è qualcosa che non mi convince.
