### ISSUE TITLE
Telecom - Monolith

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#217]
Provare a caricare la specifica Telecom dentro Monolith e vedere che succede.

**Comment by valeriosantarelli** [comment]
Un primo tentativo di caricare l'ontologia Telecom telecom_full.owl (dentro Current Mastro Specifications nella cartella di lavoro Telecom su Drive) ha prodotto il seguente errore:

-------------------  E R R O R      S T A R T  -------------------------
org.semanticweb.owlapi.model.OWLRuntimeException: Property is not a named property.  Check using the isAnonymous method before calling this method!
	at uk.ac.manchester.cs.owl.owlapi.OWLObjectInverseOfImpl.asOWLObjectProperty(OWLObjectInverseOfImpl.java:131)
	at com.mwsx.engine.ReasoningServices.getPropertyFunctional(ReasoningServices.java:842)
	at com.mwsx.engine.MwsxOntologyManager.extractObjectPropertyInfo(MwsxOntologyManager.java:612)
	at com.mwsx.engine.MwsxOntologyManager.extractOntologyOPInfo(MwsxOntologyManager.java:565)
	at com.mwsx.engine.MwsxOntologyManager.addOntologyVersion(MwsxOntologyManager.java:440)
	at com.mwsx.services.MwsxService.post__owlOntology_name_version(MwsxService.java:410)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:309)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at

**Comment by valeriosantarelli** [comment]
Il file telecom.owl invece è stato caricato.

**Comment by valeriosantarelli** [comment]
Il file di mapping nuovo non può essere caricato correttamente perchè Monolith pretende che sia specificato il nome del datasource (riferimento #226) . Riprovare non appena viene risolta la suddetta issue.

**Comment by valeriosantarelli** [comment]
Il tentativo di caricare il file di mapping ha generato un errore. Il file di mapping è compatibile con l'ontologia, tanto è vero che viene caricato. L'errore si genera quando si va nella sezione mapping per ispezionarlo (in particolare sono andato su Ontology Mapping).

[mappings_template.xml.zip](https://github.com/obdasystems/monolith/files/4397286/mappings_template.xml.zip)


×
TypeError: Cannot read property 'entityID' of null
(anonymous function)
src/pages/components/FastSearchTree.js:26
  23 | //   className += ' focused'
  24 | // }
  25 | if (this.props.counts.count) {
> 26 |   const c = this.props.counts.count.find(i => i.entity.entityID === item.entity.entityID)
     | ^  27 |   if (c) {
  28 |     label += ` (${c.numberOfMappings})`
  29 |   } else {

**Comment by giacomoronconiobda** [comment]
Puoi mettere anche il file owl

**Comment by valeriosantarelli** [comment]
[Telecom.owl.zip](https://github.com/obdasystems/monolith/files/4397428/Telecom.owl.zip)

**Comment by giacomoronconiobda** [comment]
non me lo carica il file di mapping. ottengo i seguenti errori:
```
Invalid mapping file: it may be malformed or not compliant with the ontology.
console.<computed> @ index.js:1446
r @ react_devtools_backend.js:6
reportError @ MastroApi.js:41
(anonymous) @ MastroApi.js:436
Promise.then (async)
uploadMappingFile @ MastroApi.js:425
(anonymous) @ UploadFile.js:69
(anonymous) @ utils.js:57
load (async)
getBase64 @ utils.js:54
UploadFile._this.beforeUpload @ UploadFile.js:62
Upload._this.beforeUpload @ Upload.js:288
upload @ AjaxUploader.js:118
(anonymous) @ AjaxUploader.js:86
AjaxUploader._this.uploadFiles @ AjaxUploader.js:85
AjaxUploader._this.onChange @ AjaxUploader.js:35
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:291
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:391
executeDispatchesInOrder @ react-dom.development.js:416
executeDispatchesAndRelease @ react-dom.development.js:3301
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3310
forEachAccumulated @ react-dom.development.js:3282
runEventsInBatch @ react-dom.development.js:3327
runExtractedPluginEventsInBatch @ react-dom.development.js:3537
handleTopLevel @ react-dom.development.js:3581
batchedEventUpdates$1 @ react-dom.development.js:21752
batchedEventUpdates @ react-dom.development.js:1069
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3591
attemptToDispatchEvent @ react-dom.development.js:4311
dispatchEvent @ react-dom.development.js:4232
unstable_runWithPriority @ scheduler.development.js:659
runWithPriority$1 @ react-dom.development.js:11094
discreteUpdates$1 @ react-dom.development.js:21769
discreteUpdates @ react-dom.development.js:1082
dispatchDiscreteEvent @ react-dom.development.js:4211
index.js:1446 generic: Head signature contains duplicated symbols: ID_PATH
```

**Comment by valeriosantarelli** [comment]
Lo sto sistemando, per il momento lascia stare, ti avviso quando ho finito.

**Comment by valeriosantarelli** [comment]
Ho finito di sistemare il file dei mappings, e questo corretto non mi sta dando problemi. Ho dovuto fare diverse modifiche perchè credo che qualche step nel processo di traduzione sia da rivedere (ma vabbè non credo dovremo mai più rifarlo).
Ho caricato la specifica Telecom (ontologia e mapping) sulla nostra repository di specifiche privata.
