### ISSUE TITLE
Errore dopo termine esecuzione query

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#229]
Dal log di Monolith ho riscontrato il seguente errore, sorto dopo la fine dell'esecuzione della query (barra verde, quindi secondo Monolith è tutto ok):

020-02-05 16:11:53 [SQLEngine] INFO  c.r.u.mastro.MastroStreamSQLEngine - Stop output structure detected: exiting thread loop
2020-02-05 16:11:53 [SQLEngine] INFO  c.r.u.mastro.MastroStreamSQLEngine - Waiting for predecessor to finish: viewUnf
2020-02-05 16:11:53 [SQLEngine] INFO  c.r.u.mastro.MastroStreamSQLEngine - Thread ended in 319447 ms.
2020-02-05 16:11:53 [SQLEngine] INFO  c.r.u.mastro.MastroStreamSQLEngine - Exiting
2020-02-05 16:11:53 [[QID:2/ID:new_0_e9af26ae-c417-496d-a91e-7a8d1cf4308d]] INFO  c.r.m.s.q.OBDAStreamQueryThread - Exiting
**java.sql.SQLException: Operation not allowed after ResultSet closed**
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.checkClosed(ResultSetImpl.java:437)
	at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:481)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:834)
	at it.uniroma1.dis.quonto.mapping.impl.NewJdbcGeneralMappedEvaluationResult.getConstantFromColumn(NewJdbcGeneralMappedEvaluationResult.java:309)
	at com.ruzzi.unfold.mastro.MastroStreamSQLEngine.run(MastroStreamSQLEngine.java:565)
	at java.lang.Thread.run(Thread.java:745)
**java.sql.SQLException: Operation not allowed after ResultSet closed**
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.checkClosed(ResultSetImpl.java:437)
	at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:481)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:834)
	at it.uniroma1.dis.quonto.mapping.impl.NewJdbcGeneralMappedEvaluationResult.getConstantFromColumn(NewJdbcGeneralMappedEvaluationResult.java:309)
	at com.ruzzi.unfold.mastro.MastroStreamSQLEngine.run(MastroStreamSQLEngine.java:566)
	at java.lang.Thread.run(Thread.java:745)

Credo che questo fenomeno comporti che la successiva esecuzione di una query (da un tab diverso) non vada a buon fine, perchè anche facendo girare una query semplice che dà pochi risultati in breve tempo, la barra diventa rossa, e non vengono mostrati risultati.

**Comment by roodsey** [comment]
@valeriosantarelli allegare query e specfica

**Comment by valeriosantarelli** [comment]
La specifica è sempre movieontology (allegata nei commenti alla issue #228 ).
ll comportamento l'avevo ottenuto facendo girare un pò a rotazione le prime tre query contenute in questo catalogo (sono tutt'e tre abbastanza rapide).
Se serve le allego singolarmente.

[moviequery.json.zip](https://github.com/obdasystems/monolith/files/4212916/moviequery.json.zip)

**Comment by roodsey** [comment]
Ho eseguito diverse volte le prime tre query del catalogo in sequenza:

spielberg: 3328 risultati, in pochi millisecondi
simpsons: 3143, in pochi millisecondi
james_bond: 89 risultati, in circa 5 minuti

l'errore non si è verificato.
Potrebbe essere dovuto al fatto che Monolith continua a chiedere i risultati anche dopo il termine dell'esecuzione della query, chiedo a @giacomoronconiobda di verificare.
