### ISSUE TITLE
Download Mappings

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#232]
Il pulsante di download dei mapping propone due opzioni:
- XML
- R2RML

L'opzione R2RML sembra non implementata (non fa nulla), ma in generale mi sembra che le due opzioni dovrebbero essere una alternativa all'altra (a seconda del mapping selezionato). Non credo che al momento prevediamo di far scaricare mapping Mastro in formato R2RML, nè mapping R2RML in formato Mastro.

In pratica, se ho caricato un mapping Mastro, mi aspetterei di scaricare solo un mapping Mastro, se ho caricato un mapping R2RML, mi aspetterei di scaricare solo un mapping R2RML (per il momento).

**Comment by giacomoronconiobda** [comment]
Manca aggiungiamo un parametro `format` alla rotta:

`/owlOntology/{name}/version/mapping/{mapping}`

**Comment by valeriosantarelli** [comment]
Con il mapping in allegato (ISTAT che sto rifacendo), ottengo l'errore sotto se cerco di fare il download in formato R2RML. Dice che il mapping collection è vuoto, ma ci sono sia SQL Views che Ontology Mappings dentro.

[ISTAT.mappings.zip](https://github.com/obdasystems/monolith/files/4239815/ISTAT.mappings.zip)

`-------------------  E R R O R      S T A R T  -------------------------
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
{*} 2020-02-22 19:57:31 [http-nio-8989-exec-2] ERROR com.mwsx.services.MwsxService - The mapping collection is empty
java.lang.IllegalArgumentException: The mapping collection is empty
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:498)
	at eu.optique.r2rml.api.model.impl.R2RMLMappingManagerImpl.exportMappings(R2RMLMappingManagerImpl.java:87) ~[r2rml-api-core-0.5.0.jar:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at eu.optique.r2rml.api.binding.jena.JenaR2RMLMappingManager.exportMappings(JenaR2RMLMappingManager.java:26) ~[r2rml-api-jena-binding-0.5.0.jar:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:796)
	at eu.optique.r2rml.api.binding.jena.JenaR2RMLMappingManager.exportMappings(JenaR2RMLMappingManager.java:12) ~[r2rml-api-jena-binding-0.5.0.jar:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1374)
	at it.uniroma1.dis.mastro.api.r2rml.impl.R2RMLMappingManagerAdapter.writeGraph(R2RMLMappingManagerAdapter.java:803) ~[mastro-api-1.1.2.jar:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at it	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
.uniroma1.dis.mastro.api.r2rml.impl.jena.JenaR2RMLMappingWriter.write(JenaR2RMLMappingWriter.java:62) ~[mastro-api-1.1.2.jar:na]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at it.uniroma1.dis.mastro.api.r2rml.impl.jena.JenaR2RMLMappingWriter.write(JenaR2RMLMappingWriter.java:57) ~[mastro-api-1.1.2.jar:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at com.mwsx.engine.MwsxOntologyManager.getMappingFileContent(MwsxOntologyManager.java:1521) ~[classes/:na]
	at java.lang.Thread.run(Thread.java:745)
	at com.mwsx.engine.MwsxOntologyManager.getMappingFile(MwsxOntologyManager.java:1483) ~[classes/:na]
	at com.mwsx.services.MwsxService.get__owlOntology_name_version_mapping_ID(MwsxService.java:825) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:309) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.21.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.21.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.21.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.21.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.21.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.21.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:292) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1139) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:460) [jersey-container-servlet-core-2.21.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [jersey-container-servlet-core-2.21.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) [jersey-container-servlet-core-2.21.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) [jersey-container-servlet-core-2.21.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.0.M26]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.0.M26]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:9.0.0.M26]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:498) [tomcat-coyote.jar:9.0.0.M26]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.0.M26]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:796) [tomcat-coyote.jar:9.0.0.M26]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1374) [tomcat-coyote.jar:9.0.0.M26]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.0.M26]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.0.M26]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
{*} 2020-02-22 19:57:31 [http-nio-8989-exec-2] ERROR com.mwsx.services.MwsxService - -------------------  E R R O R        E N D  -------------------------
-–1\q																		`

**Comment by giacomoronconiobda** [comment]
Il problema è generato dal mappingManager che restituisce e collezioni dei mapping vuote. Non so da cosa dipende, anche la visualizzazione sia da parte delle viste che da parte dell'ontologia restituisce 0 mappings (anche se nel file ci sono 3 mappings)

Forse il problema è che i mapping sono complex ma hanno un solo elemento nell body?
Coinvolgo @roodsey

**Comment by roodsey** [comment]
Il file contiene solo mapping di tipo "complex" (che in realtà non lo sono perché contenenti un solo atomo nel body). Credo che in generale i complex mapping non siano traducibili sempre in R2RML: occorre fare in modo che la classe it.uniroma1.dis.mastro.api.r2rml.impl.R2RMLMappingManagerAdapter (in mastro-gui-api) gestisca tale situazione. Coinvolgo Manuel per capire come procedere.
@mnamici

**Comment by valeriosantarelli** [comment]
Se non ho capito male a questo punto la distinzione tra mapping complex e simple non viene più fatta, giustamente. Monolith produce solo complex mapping, con da 1 in su viste o built-in nel body.
Se non siamo in grado di garantire la conversione Mastro-R2rml per tutti i mapping credo che la cosa più sensata sia di non proporla affatto.

**Comment by giacomoronconiobda** [comment]
I mapping sono traducibili sempre in r2rml anche i complex (viene fatto l'unfolding per la traduzione). Il problema in questo caso è che il MappingManager non li restituisce nè tra i complex nè tra i normali. Ci deve essere qualche tipo di filtro proprio a livello di parsing credo.

**Comment by valeriosantarelli** [comment]
L'operazione di Download dovrebbe in ogni caso non prevedere una "traduzione" di qualsiasi tipo dei mapping, a meno che non sia meramente una traduzione sintattica (tipo scaricare dati rdf in .ttl oppure .nt).

Direi di fare così: limitiamo l'operazione di Download allo scaricamento dei mapping così come sono stati creati/caricati (Mastro -> Mastro; R2RML -> R2RML) in modo che l'utente non ha sorprese e si ritrova esattamente quello che vedeva in Monolith.
Quindi @giacomoronconiobda questa issue si chiude limitando il download in questo modo.

Poi prevederemo la funzionalità di esportazione Mastro -> R2RML oppure R2RML -> Mastro, da implementare e posizionare in un percorso diverso all'interno di Monolith. Ora apro la issue a riguardo.

**Comment by giacomoronconiobda** [comment]
Non riesco a capire il senso di questa tuo ultimo post. Mastro non funziona nativamente con R2RML. Ogni volta i mapping vengono tradotti comunque nel nostro formato propietario. Inoltre Monolith ti permette di creare mapping che per definizione non sono R2RML. Quindi il pulsante di Download dovrebbe darti sempre un file `.mappings`

Secondo me se diciamo che supportiamo R2RML dobbiamo fare la traduzione per forza. Non c'è problema a mettere questa funzionalità Import/Export in un altro posto nell'applicazione

**Comment by valeriosantarelli** [comment]
Allora, il post sopra assume che Monolith sia in grado di caricare/fare editing di mapping sia Mastro che R2RML (so bene che al momento non è così, però questo significa solo non prevedere, per il momento, alcune delle azioni sotto elencate).

Con questa assunzione, l'operazione di Download dovrebbe funzionare così secondo me:
- Creazione da zero di un mapping Mastro -> Download -> scaricamento del file di mapping Mastro
- Caricamento di un mapping Mastro -> Download -> scaricamento del file di mapping Mastro
- Creazione da zero di un mapping R2RML  -> Download -> scaricamento del file di mapping R2RML
- Caricamento di un mapping R2RML -> Download -> scaricamento del file di mapping R2RML

In altre parole, un mapping nativamente nasce o Mastro o R2RML. L'operazione di Download permette di scaricare il mapping cos'ì com'è nato.

L'operazione di traduzione/esportazione/conversione (chiamiamola come vogliamo) invece permette di passare da Mastro a R2RML e viceversa.

**Comment by mnamici** [comment]
Ciao ragazzi, come già riportato da @giacomoronconiobda la traduzione dei mapping complex può sempre essere effettuata in R2RML, l'unica cosa che rimane fuori sono i perfect mapping (i blocchi) per i quali non abbiamo il vocabolario in R2RML per definirli, quindi non è legato al fatto che sono di tipo complex. Inoltre facendo delle prove con il plugin di Protégé con il mapping allegato l'esportazione va a buon fine ed ottengo i tre mapping in R2RML quindi il problema deve essere altrove.
