### ISSUE TITLE
Errore caricamento file .owl

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#282]
Il tentativo di caricare il file .owl in allegato produce un errore di tipo "Exception in next gnu.trove.impl.hash.THashIterator".
L'ontologia in Protégé viene caricata correttamente.

La console mi dice quanto segue:

> rror: Request failed with status code 500
    at createError (createError.js:17)
    at settle (settle.js:19)
    at XMLHttpRequest.handleLoad (xhr.js:60)
console.<computed> @ index.js:1446
DevTools failed to parse SourceMap: chrome-extension

Il log di tomcat questo:

> java.lang.StackOverflowError
-------------------  E R R O R      S T A R T  -------------------------
	at gnu.trove.impl.hash.THashIterator.next(THashIterator.java:92)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:548)
	at com.google.common.collect.Iterators.addAll(Iterators.java:361)
	at com.google.common.collect.Iterables.addAll(Iterables.java:354)
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.asSet(OWLImmutableOntologyImpl.java:692)
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.getAxioms(OWLImmutableOntologyImpl.java:178)
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.getAxioms(OWLImmutableOntologyImpl.java:167)
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.getAxioms(ConcurrentOWLOntologyImpl.java:699)
	at com.mwsx.engine.ReasoningServices.getSubClasses(ReasoningServices.java:327)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:259)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:263)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:263)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:263)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:263)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:263)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:263)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:263)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:263)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:263)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:263)
	at com.mwsx.engine.ReasoningServices.aux_buildClassTree(ReasoningServices.java:263)

[npd-v2-ql.owl.zip](https://github.com/obdasystems/monolith/files/4294982/npd-v2-ql.owl.zip)

**Comment by giacomoronconiobda** [comment]
Penso sia un problema nella generazione dell'albero dell'ontologia (va in StackOverflow)

**Comment by valeriosantarelli** [comment]
Non capisco come possano esserci problemi nella generazione dell'albero dell'ontologia se con il plugin di protègé di Mastro viene correttamente avviato il reasoner. Non ci sono particolari fenomeni tipo classi di equivalenza o altro nell albero (anche inferito).

**Comment by roodsey** [comment]
Verifico il ReasoningEngine di MWS che genera l'albero della gerarchia di concetti e classi

**Comment by roodsey** [comment]
<img width="426" alt="Screenshot 2020-03-11 at 16 05 46" src="https://user-images.githubusercontent.com/20337479/76432068-bcbc3180-63b2-11ea-96ab-9a19388f2471.png">
Il ciclo infinito è generato dall'asserzione mostrata in figura.
E' stato aggiunto un controllo: il nodo "Transfer" non verrà visualizzato come sotto node di sé stesso.
Verificare e chiudere la issue

**Comment by valeriosantarelli** [comment]
L'ontologia viene caricata correttamente. Chiudo.
