### ISSUE TITLE
Errore in fase di creazione di una inclusione

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#302]
Il tentativo di creare la seguente inclusione per i mappings di Books ha restituito l'errore che copio sotto.

    <inclusion id="id_1584523250398">
            <left arg="affiliated_writer_view[code, name]"/>
            <right arg="written_by_view[book_code, writer_id]"/>
            <description/>
        </inclusion>

L'inclusione è stata comunque scritta nel file di mapping, che allego alla issue. Quindi l'errore si ripresenta ogni volta che vado sul pannello dei vincoli dentro la pagina di questi mappings.

[mappings_2.xml.zip](https://github.com/obdasystems/monolith/files/4348044/mappings_2.xml.zip)

Se necessario aggiungo anche ontologia e mappings, fammi sapere.

java.lang.NumberFormatException: For input string: "code"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_121]
	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_121]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_121]
	at com.ruzzi.unfold.mastro.MappingManager.getViewProjection(MappingManager.java:643) ~[mastro-api-1.1.2.jar:na]
	at com.ruzzi.unfold.mastro.MappingManager.getPrimitiveViewsInclusions(MappingManager.java:1940) ~[mastro-api-1.1.2.jar:na]
	at com.ruzzi.unfold.mastro.MappingManager.getViewInclusionDependencies(MappingManager.java:1055) ~[mastro-api-1.1.2.jar:na]
	at com.mwsx.engine.MwsxOntologyManager.getMappingDependenciesByView(MwsxOntologyManager.java:2200) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.getMappingDependencies(MwsxOntologyManager.java:2367) ~[classes/:na]

**Comment by valeriosantarelli** [comment]
Il problema non si è più ripresentato, quindi per ora chiudo. Se riesco in qualche modo a rigenerarlo riapro la issue, per il momento chiudo con invalid.
