### ISSUE TITLE
Catchare errore mancanza del file Graphol

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#309]
Catchare il seguente errore che si verifica quando viene caricata una ontologia direttamente in .owl, senza il file .graphol.
L'errore si verifica all'apertura di Monolith, il quale credo vada a cercare tutti i file .graphol delle ontologie a lui note. Ovviamente non comporta problematiche, ma visto che esponiamo il log meglio evitare di mostrarlo.

{*} 2020-03-20 00:36:22 [http-nio-8989-exec-2] ERROR com.mwsx.services.MwsxService - No GRAPHOL file available for ontology imdb, version NO_VERSION_PROVIDED
java.util.NoSuchElementException: No GRAPHOL file available for ontology imdb, version NO_VERSION_PROVIDED
	at com.mwsx.engine.MwsxOntologyManager.getGrapholFileInfo(MwsxOntologyManager.java:1421) ~[classes/:na]
	at com.mwsx.services.MwsxService.get__owlOntology_name_version_graphol(MwsxService.java:723) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

**Comment by roodsey** [comment]
Raccogliere l'eccezione in modo silenzioso non è l'approccio corretto.
MWS mette a disposizione la rotta che segue:

@Path("/owlOntology/{name}/version/graphol/check")
@GET

Tale rotta restituisce un valore booleano che può essere interpretato come segue:

- true: file graphol presente
- false: file graphol assente

L'approccio che suggerisco è di utilizzare tale chiamata prima di richiedere il file graphol

**Comment by valeriosantarelli** [comment]
Ah per me va bene ovviamente. Qualsiasi sia la gestione più corretta ok.
