### ISSUE TITLE
Errore scaricamento mapping in R2RML

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#329]
Il tentativo di scaricare i mapping di ACI in R2RML genera il seguente errore (non dipendente da noi in realtà...credo).

[Archivio.zip](https://github.com/obdasystems/monolith/files/4381353/Archivio.zip)

{*} 2020-03-25 15:03:43 [http-nio-8989-exec-9] ERROR com.mwsx.services.MwsxService - error parsing SQL query SELECT /*+ optimizer_features_enable('10.2.0.5') */ RE_V_00259_0.Citta, RP_V_00259_0.dataassegnazione FROM PRA_CONS_FORMALITA.formalita F_V_00259_0, PRA_CONS_FORMALITA.REGISTROPROGRESSIVO RP_V_00259_0, PRA_CONS_FORMALITA.residenzaestera RE_V_00259_0 WHERE (F_V_00259_0.formalita = RE_V_00259_0.formalita AND F_V_00259_0.registroprogressivo = RP_V_00259_0.registroprogressivo AND RP_V_00259_0.dataassegnazione <= net.sf.jsqlparser.expression.AllComparisonExpression@30da1e)
it.uniroma1.dis.mastro.api.r2rml.impl.sql.SQLParserException: error parsing SQL query SELECT /*+ optimizer_features_enable('10.2.0.5') */ RE_V_00259_0.Citta, RP_V_00259_0.dataassegnazione FROM PRA_CONS_FORMALITA.formalita F_V_00259_0, PRA_CONS_FORMALITA.REGISTROPROGRESSIVO RP_V_00259_0, PRA_CONS_FORMALITA.residenzaestera RE_V_00259_0 WHERE (F_V_00259_0.formalita = RE_V_00259_0.formalita AND F_V_00259_0.registroprogressivo = RP_V_00259_0.registroprogressivo AND RP_V_00259_0.dataassegnazione <= net.sf.jsqlparser.expression.AllComparisonExpression@30da1e)
	at it.uniroma1.dis.mastro.api.r2rml.impl.sql.SQLUtils.aliasAllSelectExpressions(SQLUtils.java:328) ~[mastro-api-1.1.2.jar:na]
	at it.uniroma1.dis.mastro.api.r2rml.impl.R2RMLMappingManagerAdapter.addOntologyPredicateComplexMapping(R2RMLMappingManagerAdapter.java:625) ~[mastro-api-1.1.2.jar:na]
	at it.uniroma1.dis.mastro.api.r2rml.impl.R2RMLMappingManagerAdapter.addOntologyPredicateComplexMapping(R2RMLMappingManagerAdapter.java:583) ~[mastro-api-1.1.2.jar:na]
	at com.mwsx.engine.MwsxOntologyManager.getMappingFileContent(MwsxOntologyManager.java:1529) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.getMappingFile(MwsxOntologyManager.java:1494) ~[classes/:na]
	at com.mwsx.services.MwsxService.get__owlOntology_name_version_mapping_ID(MwsxService.java:852) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.21.jar:na]

**Comment by valeriosantarelli** [comment]
Notare che i mapping di ACI hanno una forma molto particolare nella SELECT delle viste, con la dicitura "/*+ optimizer_features_enable('10.2.0.5') */" legata alla versione di Oracle utilizzata a suo tempo.
Se l'errore è esclusivamente legato a questa forma particolare che il parser non riesce a gestire, credo che possiamo ignorarlo (semplicemente questi mapping in R2RML non si possono tradurre).

**Comment by mnamici** [comment]
Non credo sia legato all'utilizzo degli hint per Oracle, anche se il supporto a questi ultimi nella versione attuale è limitato dal fatto che la versione di jsqlparser utilizzata in mastro è obsoleta e non ha proprio il supporto al parsing dei commenti (li scarta a prescindere), nella peggiore delle ipotesi questi hint vengono persi durante la traduzione.

Credo sia legato ad un altro bug in jsqlparser 0.9 per cui alcune espressioni non si serializzano correttamente (in questo caso la ALL (sub-select)), ora faccio delle prove e verifico.

**Comment by mnamici** [comment]
Confermo quanto sopra, l'errore è legato ad un bug nella serializzazione in jsqlparser <= 0.9 in cui già mi ero imbattuto, che però non viene attivato dalla traduzione in R2RML ma dall'ottimizzatore.
 
Quando vengono tradotti i mapping complessi viene tentato di fare il push della FROM per evitare un livello di annidamento nella query SQL risultante, e tale ottimizzazione produce una query SQL non valida.

Dovrebbe essere possibile riprodurre l'errore anche in fase di query answering, attivando il push della FROM, ed eseguendo una query che coinvolga la vista `DataInizioStatoCittaEstera`, ad es. utilizzando  `aci:inizio_stato_del_mondo`.

Per quanto riguarda gli hint Oracle (tipo ```/*+ optimizer_features_enable('10.2.0.5') */```) ho verificato che avevo già creato un meccanismo in fase di traduzione per preservarli, sia nella forma multiriga ```/*+ hint */``` che singola riga ```--+ hint```, quindi dovrebbero sempre essere presenti nella traduzione.

**Comment by giacomoronconiobda** [comment]
L'aggiornamento di JSQL Parser sembra aver risolto la issue. Chiudo.
