### ISSUE TITLE
Errore caricamento file .graphol su Windows

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#344]
Il tentativo di creare una versione dell'ontologia partendo dal file graphol su sistema operativo Windows produce questo errore:

Domenico, 19:31
C:\Users\Fabio\mastro-home\temp\6ffd926a-8bc6-4f99-8471-9f462dcface7.owl -> C:\Users\Fabio\mastro-home\ONTO_n1949351068\VERSION_48563\ontology.owl: Impossibile accedere al file. Il file è utilizzato da un altro processo.

**Comment by savo-fabio** [comment]
Log errore caricamento file Graphol 


java.nio.file.FileSystemException: C:\Users\Fabio\mastro-home\temp\5b2d8cb7-a818-452a-bc44-33f50f0e043d.owl -> C:\Users\Fabio\mastro-home\ONTO_212725877\VERSION_48563\ontology.owl: Impossibile accedere al file. Il file � utilizzato da un altro processo.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[na:1.8.0_121]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[na:1.8.0_121]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387) ~[na:1.8.0_121]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[na:1.8.0_121]
	at java.nio.file.Files.move(Files.java:1395) ~[na:1.8.0_121]
	at com.mwsx.engine.MwsxOntologyManager.addOntologyVersion(MwsxOntologyManager.java:645) ~[mws-server-1.0.0.jar:na]
	at com.mwsx.services.MwsxService.post__owlOntology_name_version(MwsxService.java:439) ~[mws-server-1.0.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:309) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:292) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1139) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:460) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) [mws-server-1.0.0.jar:na]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) [mws-server-1.0.0.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760) [mws-server-1.0.0.jar:na]

**Comment by valeriosantarelli** [comment]
La problematica persiste.
Riscontrata sia sul PC di Fabio che sul mio Windows.


*} 2020-04-06 17:36:07 [qtp26449037-16] ERROR com.mwsx.services.MwsxService - -------------------  E R R O R      S T A R T  -------------------------
-------------------  E R R O R      S T A R T  -------------------------
java.nio.file.FileSystemException: C:\Users\olimp\mastro-home\temp\56837de2-60be-4397-9eee-9023e1f0193e.owl -> C:\Users\olimp\mastro-home\ONTO_64369290\VERSION_48563\ontology.owl: Impossibile accedere al file. Il file � utilizzato da un altro processo.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at com.mwsx.engine.MwsxOntologyManager.addOntologyVersion(MwsxOntologyManager.java:659)
	at com.mwsx.services.MwsxService.post__owlOntology_name_version(MwsxService.java:442)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
