### ISSUE TITLE
Retrocompatibilità nel caricamento di un file di mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#346]
Bisogna garantire retrocompatibilità rispetto ai file di mapping generati per il plugin di protégé.
Allo stato attuale, questi mapping non vengono caricati perché manca il tag "mappingsMetadata" nel file XML (errore riportato sotto).

Allego un file per replicare l'errore: 
[original-mappings.xml.zip](https://github.com/obdasystems/monolith/files/4392375/original-mappings.xml.zip)

Ovviamente si possono generare le informazioni presenti nel tag mappingsMetadata in modo default, usando come id l'id dell'ontologia e come version la versione dell'ontologia scelta al momento del caricamento (e naturalmente descrizione vuota).

it.uniroma1.dis.quonto.mapping.exceptions.MappingFileMalformedException: One and only one 'mappingsMetadata' element must be present in XML specification file
	at com.mwsx.engine.MwsxOntologyManager.getMappingID(MwsxOntologyManager.java:1547) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.postMapping(MwsxOntologyManager.java:1497) ~[classes/:na]
	at com.mwsx.services.MwsxService.post__owlOntology_name_version_mapping_ID(MwsxService.java:886) ~[classes/:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:309)

**Comment by roodsey** [comment]
Modificata rotta
```
/owlOntology/{name}/version/mapping
```
con aggiunta di parametro di query
```
checkDeprecation
```
se posto pari a true nel risultato di verifica del mapping vengono specificati i messaggi relativi al formato XML dei mapping, appositamente inseriti in una collezione di stringhe "deprecated"
