### ISSUE TITLE
Query report Card

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#349]
Aggiungere alla card del query report le informazioni relative all'esecuzione di una query EQL.

Mi immaginerei una cosa del genere:
- in caso di query EQL, viene visualizzato un tab PRIMA di Ontology Rewritings, chiamato EQL Queries, in cui vengono mostrate tutte le query SPARQL che hanno alimentato le SPARQL Tables, e la query SQL finale
- in caso di query CQ, questo tab non viene mostrato

E' fattibile?

**Comment by roodsey** [comment]
Aggiunta rotta
```
/endpoint/{name}/query/{queryID}/eqlDetails
```
che restituisce un oggetto contenente la lista degli ID delle SPARQL tables eseguite per questa query EQL. Da tali ID si possono recuperare le informazioni sulle esecuzioni delle singole query con la rotta già presente per lo "status"

**Comment by giacomoronconiobda** [comment]
La successiva chiamata sulla rotta già presente per lo "status" resituisce il seguente errore:

```
java.lang.RuntimeException: Cannot find Catalog ID V1 in query ID map-------------------  E R R O R      S T A R T  -------------------------

	at com.ruzzi.mastro.stream.queries.monitor.OBDAMainMemoryQueryMonitor.getQid(OBDAMainMemoryQueryMonitor.java:73)
	at com.ruzzi.mastro.stream.queries.monitor.OBDAMainMemoryQueryMonitor.getQueryRecordById(OBDAMainMemoryQueryMonitor.java:336)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.mtq_getQueryRecord(MastroAPI.java:5618)
	at com.mwsx.engine.MwsxOntologyManager.getQueryStatus(MwsxOntologyManager.java:2740)
	at com.mwsx.services.MwsxService.get__owlOntology_name_version_query_ID_status(MwsxService.java:2672)
```
