### ISSUE TITLE
Implementazione controlli Mapping Version

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#352]
Implementare i controlli di duplicazione utilizzando la versione di un mapping, e non il nome.
Siccome è una informazione che gestiamo, tanto vale che la usiamo (anche per essere consistenti con quanto facciamo con le ontologie).

Per riferimento, adesso se viene caricato un mapping che ha versione diversa ma nome uguale di uno già esistente, l'errore riportato è il seguente:

{*} 2020-03-28 16:37:19 [http-nio-8989-exec-10] ERROR com.mwsx.services.MwsxService - Duplicated mapping ID telecom_mappings
java.lang.RuntimeException: Duplicated mapping ID telecom_mappings
	at com.mwsx.engine.MwsxOntologyManager.postMapping(MwsxOntologyManager.java:1509)
	at com.mwsx.services.MwsxService.post__owlOntology_name_version_mapping_ID(MwsxService.java:913)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at com.mwsx.engine.MwsxOntologyManager.postMapping(MwsxOntologyManager.java:1509) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.mwsx.services.MwsxService.post__owlOntology_name_version_mapping_ID(MwsxService.java:913) ~[classes/:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)

**Comment by valeriosantarelli** [comment]
Dopo la fusione di Version e ID, questa issue non è più rilevante.
