### ISSUE TITLE
Errore creazione endpoint per ontologia IMDB

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#366]
La creazione dell'endpoint per IMDB genera il seguente errore (l'OWL ha dentro delle asserzioni che determinano una ABox).
In allegato la cartella con la specifica.

Exception in thread "Thread-48" java.lang.NullPointerException
	at it.uniroma1.dis.mastro.parsers.MastroOWLParser.createABoxTables(MastroOWLParser.java:3833)
	at it.uniroma1.dis.mastro.parsers.MastroOWLParser.createABoxMappingsAndData(MastroOWLParser.java:3216)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.loadOWLAssertions(MastroAPI.java:5125)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.createOntology(MastroAPI.java:1658)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.createOntology(MastroAPI.java:1304)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.propertiesInit(MastroAPI.java:7735)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.init(MastroAPI.java:4931)
	at com.mwsx.engine.MwsxMastroInstanceLoader.run(MwsxMastroInstanceLoader.java:32)
	at java.lang.Thread.run(Thread.java:745)

[ONTO_3236002.zip](https://github.com/obdasystems/monolith/files/4425854/ONTO_3236002.zip)

**Comment by valeriosantarelli** [comment]
Come per magia, la issue non si presenta più. Chiudo.
