### ISSUE TITLE
Errore esecuzione query EQL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#369]
Le query EQL che utilizzano le IRI completi delle entity invece che i nomi prefissati vengono tradotte in modo errato.

Ad esempio:

select ?name where {
	?director a <http://dbpedia.org/page/Film_Director>.
	?director <http://www.movieontology.org/ontology/name> ?name
	FILTER(NOT EXISTS{?movie <http://www.movieontology.org/ontology/hasDirector> ?director. 
      ?movie <http://www.movieontology.org/ontology/gross> ?gross. 
      ?movie <http://www.movieontology.org/ontology/budget> ?budget. FILTER(?budget > ?gross)})

}

produce questo errore:

SELECT ?director ?name WHERE { 	?director http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://dbpedia.org/page/Film_Director.
		?director :name ?name.
 }
	at it.uniroma1.dis.mastro.parsers.SparqlUCQParser.parseSparqlUCQ(SparqlUCQParser.java:418)
	at com.ruzzi.mastro.stream.queries.OBDAStreamQueryThread.init(OBDAStreamQueryThread.java:326)
	at com.ruzzi.mastro.stream.queries.OBDAStreamQueryThread.<init>(OBDAStreamQueryThread.java:165)
	at com.ruzzi.mastro.stream.queries.OBDAQueryRunner.run(OBDAQueryRunner.java:149)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.jena.query.QueryParseException: Line 41, column 43: Unresolved prefixed name: http:
	at org.apache.jena.sparql.lang.ParserBase.throwParseException(ParserBase.java:522)
	at org.apache.jena.sparql.lang.ParserBase.resolvePName(ParserBase.java:287)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.PrefixedName(SPARQLParser11.java:4861)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.iri(SPARQLParser11.java:4841)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.PathPrimary(SPARQLParser11.java:2873)

Questo perchè nella prima query SPARQL prodotta, vengono persi i caratteri "<" e ">", e rimane solo "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" e "http://dbpedia.org/page/Film_Director".
Quindi il parser pensa che "http" sia un prefisso, quando ovviamente non lo è. 

EDIT: ho fatto una ulteriore prova, e il problema si presenta anche quando si usa il predicate "a" al posto di rdf:type. La "a" viene rimpiazzata con l'IRI completa di rdf:type, però vengono persi per strada i tag di apertura e chiusura della IRI.

**Comment by valeriosantarelli** [comment]
La query in oggetto è la "IMDB1" del catalogo full di IMDB: https://raw.githubusercontent.com/obdasystems/OBDA-Specifications/master/movieontology/1.0.1/moviequeryFULL.json

**Comment by roodsey** [comment]
La query in questione ora gira: ho però preventivamente dovuto aggiungere un namespace mancante poiché Film_Director è in dbpedia e non in imdb. Dopo circa 25 minuti l'ho interrotta perché continuava a caricare dati della sparql table. Questa query ci servirà per analizzare i limiti di EQL come motore di query real-time.
