### ISSUE TITLE
Eliminare endpoint all'eliminazione di una ontologia

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#382]
Quando si cancella una ontologia da Monolith, è necessario anche eliminare qualsiasi endpoint ad essa collegata.

Altrimenti rimangono appesi, e quando si prova a interagirci, esce fuori un errore di questo tipo:
java.lang.RuntimeException: Cannot find mapping file for mapping ID books_mappings
	at com.mwsx.engine.MwsxRepositoryManager.getMappingFilePath(MwsxRepositoryManager.java:139)
	at com.mwsx.engine.MwsxCacheManager.getMappingManager(MwsxCacheManager.java:234)
	at com.mwsx.engine.MwsxCacheManager.startEndpoint(MwsxCacheManager.java:360)
	at com.mwsx.engine.MwsxOntologyManager.startEndpoint(MwsxOntologyManager.java:4644)
	at com.mwsx.services.MwsxService.start_endpoint(MwsxService.java:2442)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)

**Comment by giacomoronconiobda** [comment]
Questo è un altro tipo di drop cascade. Siamo sicuri che non vogliamo gestirlo lato mws? @roodsey

**Comment by giacomoronconiobda** [comment]
Lo prendo per un si
