### ISSUE TITLE
Errore Connessione Database anche da Mac 

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#385]
Segnalo che anche su Mac sto riscontrando, da stamattina, il medesimo errore di connessione al database visto su Windows, per database mySQL localizzati (#332 ).
Riporto l'errore sotto.

Se valutiamo che è normale (prima dell'ultimo aggiornamento non succedeva), possiamo tranquillamente chiudere, adottando la soluzione proposta per la #332 sta funzionando tutto. E' solo per segnalarlo.

it.uniroma1.dis.quonto.core.datasourcemanager.exceptions.DataLevelSQLError: Data Source SQL Error when establishing Database connection: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at it.uniroma1.dis.quonto.core.datasourcemanager.impl.MySqlDataSourceManager.createConnection(MySqlDataSourceManager.java:189)
	at it.uniroma1.dis.quonto.core.datasourcemanager.impl.MySqlDataSourceManager.getConnection(MySqlDataSourceManager.java:111)
	at it.uniroma1.dis.mastro.parsers.MastroOWLParser.createABoxMappingsAndData(MastroOWLParser.java:3209)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.loadOWLAssertions(MastroAPI.java:5125)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.createOntology(MastroAPI.java:1658)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.createOntology(MastroAPI.java:1304)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.propertiesInit(MastroAPI.java:7739)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.init(MastroAPI.java:4931)
	at com.mwsx.engine.MwsxMastroInstanceLoader.run(MwsxMastroInstanceLoader.java:32)
	at java.lang.Thread.run(Thread.java:745)
it.uniroma1.dis.obda.OBDAReasonerException: it.uniroma1.dis.quonto.core.datasourcemanager.exceptions.DataLevelSQLError: Data Source SQL Error when establishing Database connection: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.createOntology(MastroAPI.java:1664)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.createOntology(MastroAPI.java:1304)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.propertiesInit(MastroAPI.java:7739)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.init(MastroAPI.java:4931)
	at com.mwsx.engine.MwsxMastroInstanceLoader.run(MwsxMastroInstanceLoader.java:32)
	at java.lang.Thread.run(Thread.java:745)

**Comment by giacomoronconiobda** [comment]
A me era successo anche su Ubuntu. Penso che non dipenda dal OS ma piuttosto dalla versione di MySql

**Comment by valeriosantarelli** [comment]
Vabbè allora a posto così. La scritta che viene fuori è più che sufficiente.
