### ISSUE TITLE
Salvataggio di più keys

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#396]
Se provo a definire più di una key per una vista, il sistema salva sempre la prima che ho definito, tante volte quante sono le key diverse inserite.

- [x] Nell'esempio sotto, avevo definito una key su hernr e una su bez, e il risultato è due key su hernr.

<img width="766" alt="Schermata 2020-04-17 alle 11 03 33" src="https://user-images.githubusercontent.com/8250758/79552346-2fe45200-809b-11ea-96eb-c3a5d7996a28.png">

- [x] Aggiungo che se poi provo a fare edit sulla vista, mi fa vedere una sola key.

<img width="950" alt="Schermata 2020-04-17 alle 11 05 11" src="https://user-images.githubusercontent.com/8250758/79552460-586c4c00-809b-11ea-9fc0-58f4540401d9.png">

**Comment by giacomoronconiobda** [comment]
Ho controllato le chimate e sono giuste, l'errore sembra provenire dai servizi e si presenta anche 
quando si mette una chiave non sul primo campo della vista. Per esempio:
### View
```
select x, y from t
```
### Key
```
(y)
```
Chiamate eseguite:
1. `POST owlOntology/WolfOil/version/mapping/mapping_wolf/views`
2. `POST owlOntology/WolfOil/version/mapping/mapping_wolf/dependencies/keys`

**Comment by valeriosantarelli** [comment]
Quando salvo la vista con le due keys, ora il sistema produce il seguente errore. Fatemi sapere se posso dare delle indicazioni dalla console.

{*} 2020-04-18 10:20:37 [http-nio-8989-exec-4] ERROR com.mwsx.services.MwsxService - Field index out of bounds!
java.util.NoSuchElementException: Field index out of bounds!
	at com.ruzzi.unfold.model.ViewDefinition.getHeadField(ViewDefinition.java:160) ~[mastro-api-1.2.1.jar:na]
	at com.mwsx.engine.MwsxOntologyManager.convert(MwsxOntologyManager.java:2521) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.extractQuarantined(MwsxOntologyManager.java:2405) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.getMappingDependenciesByView(MwsxOntologyManager.java:2381) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.getViewMappings(MwsxOntologyManager.java:2346) ~[classes/:na]
	at com.mwsx.services.MwsxService.get__owlOntology_name_version_mapping_ID_views_viewID(MwsxService.java:1338) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]

**Comment by roodsey** [comment]
La issue non sussiste: si veda l'immagine di seguito.
Allego anche il file di mapping generato (la query SQL è puramente sintattica espressa sullo schema IMDB, per semplicità).
![image](https://user-images.githubusercontent.com/20337479/79732491-0bcf7d80-82f4-11ea-9129-3dd910d70bd1.png)
[mappings_1.xml.zip](https://github.com/obdasystems/monolith/files/4502211/mappings_1.xml.zip)

**Comment by valeriosantarelli** [comment]
E' possibile che il problema sia lo stesso evidenziato nella #404 ?
In caso chiudiamo questa.

**Comment by giacomoronconiobda** [comment]
sembra di si: Marco usa gli alias e non vede bug, Valerio non li usa e vede bug

**Comment by roodsey** [comment]
Non mi pare ci siano problemi neanche evitando di utilizzare gli alias:

![image](https://user-images.githubusercontent.com/20337479/79754107-4ac2fa80-8317-11ea-89ba-07128d230b3d.png)

![image](https://user-images.githubusercontent.com/20337479/79754164-63cbab80-8317-11ea-80aa-6cc69c8b3ca8.png)

**Comment by valeriosantarelli** [comment]
Allora, dei due problemi riscontrati inizialmente, il primo è risolto, il secondo si presenta ancora.

Ho messo le checkbox per evidenziare meglio che ci sono due problematiche diverse segnalate.

**Comment by valeriosantarelli** [comment]
Le checkbox sono tutt'e due checkate, significa che la issue è chiusa?
