### ISSUE TITLE
Errore apertura pagina Mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#404]
L'apertura della pagina dei mapping, per mapping creati da zero dentro Monolith, produce questo errore.

Per replicare si può usare sempre Wolf.

java.util.NoSuchElementException: Field index out of bounds!
	at com.ruzzi.unfold.model.ViewDefinition.getHeadField(ViewDefinition.java:160)
	at com.mwsx.engine.MwsxOntologyManager.convert(MwsxOntologyManager.java:2521)
	at com.mwsx.engine.MwsxOntologyManager.extractQuarantined(MwsxOntologyManager.java:2405)
	at com.mwsx.engine.MwsxOntologyManager.getMappingDependenciesByView(MwsxOntologyManager.java:2381)
	at com.mwsx.engine.MwsxOntologyManager.getMappingDependencies(MwsxOntologyManager.java:2600)
	at com.mwsx.services.MwsxService.get__owlOntology_name_version_mapping_ID_dependencies(MwsxService.java:1365)
	at sun.reflect.GeneratedMethodAccessor206.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)

**Comment by roodsey** [comment]
Ho completato i passi seguenti:
1 -  creato una nuova ontologia
2 - caricato la versione WolfOil.owl
3 - creato un nuovo file di mapping da monolith
4 - creato una vista
5 - creato un mapping
6 - visualizzato la pagina dei mapping

Tutto regolare, suggerisco di verificare bene la chiamata fatta da Monolith a fronte dell'errore riscontrato. Per il momento mi limito a rendere il messaggio più chiaro.

Un po' di immagini di repertorio corredano quanto analizzato.

![image](https://user-images.githubusercontent.com/20337479/79730553-4c79c780-82f1-11ea-9f4e-0c1cc64fed5f.png)

![image](https://user-images.githubusercontent.com/20337479/79730603-5d2a3d80-82f1-11ea-8d4f-32dc13197eb7.png)

**Comment by giacomoronconiobda** [comment]
Leggendo la traccia dell'erorre mws penso dipendi dalla specifica vista. Valerio puoi allegare la specifica?

**Comment by valeriosantarelli** [comment]
Allora, potrebbe avere a che fare con le dependencies.
Io avevo creato due viste, e definito le Keys per tutt'e due. In particolare, per una era definita una key con due campi.

Allego la specifica.
[ONTO_n1110864384.zip](https://github.com/obdasystems/monolith/files/4502184/ONTO_n1110864384.zip)


Da Network sulla console di Chrome, mi dà questo errore:

![Schermata 2020-04-20 alle 10 37 15](https://user-images.githubusercontent.com/8250758/79731819-1c332880-82f3-11ea-8900-c50af6f15389.png)

**Comment by giacomoronconiobda** [comment]
Penso il problema sia in questa parte dell'xml (le dependency cominciano a contare da 1):
```
<key id="kd_1587198037022">
            <projection arg="engine_manufacturers[1]"/>
            <description/>
        </key>
    <key id="kd_1587198037058">
            <projection arg="engine_manufacturers[0]"/>
            <description/>
        </key>
```

**Comment by valeriosantarelli** [comment]
Si, credo anche io, ho riprovato a creare quella vista e aggiungere le due keys, e ora mi dà questo errore:

{*} 2020-04-20 10:58:11 [http-nio-8989-exec-7] ERROR com.mwsx.services.MwsxService - Error processing view key dependency kd_1587198037058 (Key := engine_manufacturers[0])
java.lang.RuntimeException: Error processing view key dependency kd_1587198037058 (Key := engine_manufacturers[0])
	at com.mwsx.engine.MwsxOntologyManager.convert(MwsxOntologyManager.java:2529) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.extractQuarantined(MwsxOntologyManager.java:2405) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.getMappingDependenciesByView(MwsxOntologyManager.java:2381) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.getMappingDependencies(MwsxOntologyManager.java:2605) ~[classes/:na]
	at com.mwsx.services.MwsxService.get__owlOntology_name_version_mapping_ID_dependencies(MwsxService.java:1365) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]

A chi devo assegnare?

**Comment by giacomoronconiobda** [comment]
Penso sia un problema di come mws genera la testa delle viste e delle chiavi (non stai usando gli alias). Lato Monolith mi sembrano giuste le chiamate. Coinvolgerei @roodsey con queste specifiche rotte (semplificate per agevolare la lettura):
```
POST /views

{"sqlViewID":"engine_manufacturers","sqlViewDescription":"","sqlViewCode":"SELECT DISTINCT op155.hernr,\n    op012.bez\n   FROM operational.op155_engines op155,\n    operational.op100_manufacturer op100,\n    operational.op012_country_and_language_dependent_descriptions op012\n  WHERE op155.hernr = op100.hernr AND op100.lbeznr = op012.lbeznr AND op012.sprachnr = 4"}

POST /keys

{"id":"kd_1587375919430","description":"","sqlViewID":"engine_manufacturers","keyHead":["op155.hernr"]}

POST /keys

{"id":"kd_1587375919535","description":"","sqlViewID":"engine_manufacturers","keyHead":["op012.bez"]}

**Comment by giacomoronconiobda** [comment]
Ho sbagliato a chiudere, sorry

**Comment by valeriosantarelli** [comment]
Il problema è la forma della select:

`SELECT DISTINCT op155.hernr,
    op012.bez`

Il parsing della select non va a buon fine se si usa il punto (quindi nome_tabella.nome_colonna) e NON si usa l'alias.
Se si usa l'alias senza punto, non ci sono problemi. Se si usa il punto e si usa l'alias, non ci sono problemi.

**Comment by giacomoronconiobda** [comment]
Ho messo il controllo degli alias nella select. Suggerirei di metterlo anche su JSQLParser
