### ISSUE TITLE
Errore durante esecuzione di query Construct

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#416]
L'esecuzione di query construct a volte, ma NON sempre (stamattina ho eseguito la query sotto due volte di fila, la prima volta l'ha fatto, la seconda tutto bene), produce l'errore riportato sotto.

`{*} 2020-04-24 10:01:14 [http-nio-8989-exec-4] ERROR com.mwsx.services.MwsxService - -------------------  E R R O R      S T A R T  -------------------------
it.uniroma1.dis.mastro.api.exceptions.MastroRuntimeException: Cannot find Construct detail for query with ID=santaroni_neverland_C_CQ
-------------------  E R R O R      S T A R T  -------------------------
{*} 2020-04-24 10:01:14 [http-nio-8989-exec-4] ERROR com.mwsx.services.MwsxService - Cannot find Construct detail for query with ID=santaroni_neverland_C_CQ
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.mtq_constructGetMappingRewriting(MastroAPI.java:8406)
	at com.mwsx.engine.MwsxOntologyManager.getConstructQueryStatus(MwsxOntologyManager.java:3182)
it.uniroma1.dis.mastro.api.exceptions.MastroRuntimeException: Cannot find Construct detail for query with ID=santaroni_neverland_C_CQ
	at com.mwsx.services.MwsxService.get__owlOntology_name_version_construct_query_ID_status(MwsxService.java:2893)
	at it.uniroma1.dis.mastro.api.impl.MastroAPI.mtq_constructGetMappingRewriting(MastroAPI.java:8406) ~[mastro-api-1.2.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at com.mwsx.engine.MwsxOntologyManager.getConstructQueryStatus(MwsxOntologyManager.java:3182) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.mwsx.services.MwsxService.get__owlOntology_name_version_construct_query_ID_status(MwsxService.java:2893) ~[classes/:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMet`

Stamattina la query che ha generato questo errore era Neverland_C_CQ del catalogo per i test sulla specifica Books:
`construct {?x :name ?nome. 
  			?x :edited  'Neverland'^^xsd:string}
Where { ?x a :Editor.
        ?x :name ?nome.
        ?y :editedBy ?x.
        ?z :hasEdition ?y.
        ?z :title 'Neverland'^^xsd:string }`

Non so se è un problema lato servizi oppure di esecuzione vera e propria della construct, quindi coinvolgo sia @roodsey che @NonnonePalmiro .

**Comment by valeriosantarelli** [comment]
Anche la query Abilities_C_EQL (eseguita ovviamente in modalità EQL) sulla specifica Superheroes mi ha generato il medesimo errore.
Questa forse però è più significativa, perchè genera l'errore ad ogni esecuzione.
Notare che questa query è EQL e Construct insieme.

**Comment by roodsey** [comment]
Da quello che ho potuto provare l'errore è interno a MastroAPI, specificamente nei metodi per la gestione delle construct. Al momento mi rimuovo dalla issue, in caso di necessità fatemi sapere.

**Comment by NonnonePalmiro** [comment]
L'errore nel primo caso (construct su UCQ) era dovuto alla richiesta delle informazioni relative ai rewriting prima che gli elementi corrispondenti fossero inseriti nel query monitor, e per queste query ho committato una modifica che dovrebbe risolvere il problema.

Per quanto riguarda la seconda query , questa appartiene ad una classe di query che al momento non trattiamo proprio, cioè construct con dentro subquery eql, e quindi la query non passa nemmeno il controllo del parser (a questo proposito, suggerirei di introdurre il controllo sintattico sulle direttamente tra le chiamate di Monolith, in modo che solo query legali possano raggiungere il server evitando una serie di possibili situazioni non previste). Il motore delle query Construct che ho scritto io prevede che nel corpo (clausola where) sia presente una query SPARQL direttamente traducibile in una UCQ standard con la possibilità di  aggiungere clausole "LIMIT" ed "ORDER BY"(non mi ricordo se a livello globale della UCQ o per singola CQ). Io credevo che il codice fosse stato modificato per prevedere anche l'esecuzione di questa nuova famiglia di query, ma da quello che ho potuto vedere non è questo il caso, dunque se alcune query di questa famiglia girano e restituiscono risultati lo fanno, per quanto ne sappia io, per caso

**Comment by valeriosantarelli** [comment]
Sul primo punto confermo, ho lanciato una decida di esecuzioni in successione, e non è mai ricomparso l'errore.

Sul secondo punto in effetti non sono del tutto sorpreso. Ho inserito nelle specifiche per i test di integrazione delle query combinate Construct-EQL proprio per essere sicuri, in un modo o nell'altro, di quale fosse la situazione. Questo errore quindi è a ulteriore conferma.

A questo punto chiudo questa issue, e apro su Mastro la issue per il supporto alle query Construct-EQL.
