### ISSUE TITLE
Errore creazione/edit di una inclusion

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#421]
Un tentativo di creare o modificare una inclusion sulla specifica books genera il seguente errore:

java.lang.NoClassDefFoundError: org/junit/Assert
	at com.mwsx.engine.MwsxOntologyManager.convertTermListToPosition(MwsxOntologyManager.java:5145)
	at com.mwsx.engine.MwsxOntologyManager.generateMappingInclusionNode(MwsxOntologyManager.java:5130)
	at com.mwsx.engine.MwsxOntologyManager.postMappingDependenciesInclusions(MwsxOntologyManager.java:5103)
	at com.mwsx.services.MwsxService.post__owlOntology_name_version_mapping_ID_dependencies_inclusions(MwsxService.java:1409)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

L'inclusion che stavo cercando di scrivere è
unedited_view(code,title,typ) -> book_view(code,title,typ)

sulla specifica di mapping che allego (modificata rispetto a quella originale per ampliare la segnatura della vista unedited_view.

[mappings_2.xml.zip](https://github.com/obdasystems/monolith/files/4551630/mappings_2.xml.zip)

<img width="1018" alt="Schermata 2020-04-29 alle 14 29 48" src="https://user-images.githubusercontent.com/8250758/80596165-391fd800-8a26-11ea-873e-5fd8c6ff13dd.png">

**Comment by roodsey** [comment]
L'errore non si presenta nella mia installazione: l'eccezione NoClassDefFoundError lascia supporre problemi di build (forse dovuti agli ultimi aggiornamenti fatti per il corretto trattamento delle dipendenze dei driver JDBC). Suggerisco un clean + rebuild di tutti i progetti.

![image](https://user-images.githubusercontent.com/20337479/80945740-c4b1b400-8dec-11ea-8803-2884c52fa4e3.png)

**Comment by giacomoronconiobda** [comment]
L'errore è dovuto al fatto che nei build non viene incluso la dipendenza
junit. Alcune classi vengono effettivamente usate a runtime e non solo dai
test unitari. Sarebbe secondo me opportuno non usare le classi junit a
runtime.

Il lun 4 mag 2020, 09:52 Marco Ruzzi <notifications@github.com> ha scritto:
