### ISSUE TITLE
Gestione dell'uso del ; alla fine delle query nelle Viste

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#438]
Nel file di mapping in allegato, prodotto da un partecipante al corso di formazione fatto per ISTAT, una view è fatta in questo modo:

`select bk_code as id, bk_title,bk_type from books.tb_books;`

[mappingbooks.xml.zip](https://github.com/obdasystems/monolith/files/4672151/mappingbooks.xml.zip)

C'è quindi il punto e virgola alla fine della query.

Questa View crea problemi sia in Protégé che in Monolith se si fa una query SPARQL che la coinvolge.

In Monolith l'errore prodotto è il seguente:

```
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ';) V_00007_0' at line 4
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at it.uniroma1.dis.quonto.mapping.impl.NewJdbcGeneralMappedEvaluationResult.nextRow(NewJdbcGeneralMappedEvaluationResult.java:421)
	at com.ruzzi.unfold.mastro.MastroStreamSQLEngine.run(MastroStreamSQLEngine.java:549)
	at java.lang.Thread.run(Thread.java:745)
it.uniroma1.dis.quonto.core.exceptions.OntologyAlphabetException: REALLY AN SQL ERROR: 
MESSAGE:You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ';) V_00007_0' at line 4
SQL-CODE: SELECT 
  V_00007_0.id
FROM 
  (select bk_code as id, bk_title,bk_type from books.tb_books;) V_00007_0
	at it.uniroma1.dis.quonto.mapping.impl.NewJdbcGeneralMappedEvaluationResult.nextRow(NewJdbcGeneralMappedEvaluationResult.java:462)
	at com.ruzzi.unfold.mastro.MastroStreamSQLEngine.run(MastroStreamSQLEngine.java:549)
	at java.lang.Thread.run(Thread.java:745)
```

Bisogna quindi gestire la possibilità che un utente inserisca il punto e virgola dentro una query SQL nelle view o nei mapping. Si potrebbe semplicemente togliere quando la query viene parsata.

**Comment by valeriosantarelli** [comment]
Se inserisco il punto e virgola alla fine della query della vista, il parser mi dice che c'è un errore nella query. La query poi la fa salvare, ma il punto e virgola viene rimosso.

La seconda parte va bene (ovvero che il sistema toglie il punto e virgola), è la prima parte che non è particolarmente elegante, perchè il messaggio di errore segnalato è "Only SELECT statements are allowed": questo non aiuta l'utente in alcun modo a capire che il problema con la sua query è il punto e virgola finale, e siccome in linea di massima una query SQL va sempre terminata con il punto e virgola, non credo che sia accettabile, si rischia solo di creare confusione.

O non segnaliamo alcun errore se c'è il ; e semplicemente lo togliamo dopo, oppure scriviamo una nota sotto l'area di test dell'SQL Code dicendo che il ; si può omettere, oppure segnaliamo un errore ma specifichiamo un messaggio che evidenzia il problema giusto. O qualsiasi altra soluzione che però non comporta che all'utente venga segnalato un errore senza fargli capire qual'è il problema.

<img width="636" alt="Schermata 2020-06-09 alle 10 15 52" src="https://user-images.githubusercontent.com/8250758/84123860-b59cd200-aa3a-11ea-83df-b948a79f0074.png">
