### ISSUE TITLE
Errore apertura pagina mapping by Entity

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#444]
Quando apro la pagina degli Ontology Mappings "by entity" con la specifica in allegato, viene restituito il seguente errore:

```
java.lang.NullPointerException: null
	at com.mwsx.engine.MwsxOntologyManager.getOntologyEntityByIRI(MwsxOntologyManager.java:5436) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.getMappingCount(MwsxOntologyManager.java:5408) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at com.mwsx.services.MwsxService.get__owlOntology_name_version_mapping_ID_coount(MwsxService.java:1193) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor356.invoke(Unknown Source) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
```

[Archivio 2.zip](https://github.com/obdasystems/monolith/files/4689938/Archivio.2.zip)

![Schermata 2020-05-27 alle 18 01 45](https://user-images.githubusercontent.com/8250758/83044208-2c51cc80-a044-11ea-9d29-53debaa3e976.png)

**Comment by valeriosantarelli** [comment]
L'errore dipende o dalla presenza di una classe che ha un accento nel nome (Proprietà_UI), oppure dal prefisso "UIE" che corrisponde ad un namespace che non ha un separatore finale.

Ho modificato queste due cose togliendo l'accento e inserendo il separatore nel namespace, e ora l'errore non viene più mostrato (e i mapping vengono conteggiati correttamente).

Ad ogni modo tutt'e due le situazioni sono da gestire.

**Comment by roodsey** [comment]
[esUi.owl.zip](https://github.com/obdasystems/monolith/files/4700469/esUi.owl.zip)

**Comment by roodsey** [comment]
Il carattere accentato non è un problema: l'errore derivava da una mancata risoluzione del prefisso senza carattere terminatore (/ oppure #). Ho implementato una fix che cerca il prefisso manualmente quando necessario, in fase di costruzione del catalogo delle entità dell'ontologia
