### ISSUE TITLE
Errore creazione Key

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#447]
Il tentativo di creare una key ha prodotto il seguente errore:

```
23:39:23.074 [http-nio-8989-exec-10] ERROR com.mwsx.services.MwsxService - Error processing view key dependency kd_1590615562776 (Key := Tipo_Uso_Catastale_view[0])
java.lang.RuntimeException: Error processing view key dependency kd_1590615562776 (Key := Tipo_Uso_Catastale_view[0])
	at com.mwsx.engine.MwsxOntologyManager.convert(MwsxOntologyManager.java:2637) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.extractQuarantined(MwsxOntologyManager.java:2513) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.getMappingDependenciesByView(MwsxOntologyManager.java:2489) ~[classes/:na]
	at com.mwsx.engine.MwsxOntologyManager.getViewMappings(MwsxOntologyManager.java:2454) ~[classes/:na]
	at com.mwsx.services.MwsxService.get__owlOntology_name_version_mapping_ID_views_viewID(MwsxService.java:1710) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.21.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.21.jar:na]

```

Allego la specifica: [Archivio 3.zip](https://github.com/obdasystems/monolith/files/4691984/Archivio.3.zip)

In particolare la vista è la seguente:

```
<primitiveView id="Tipo_Uso_Catastale_view">
            <HEAD string="Tipo_Uso_Catastale_view(idTipoUso, categoria, descCategoria, tipoUso, descTipoUso)"/>
            <SQLQuery>select v.ID_TIPO_USO_CATASTALE as idTipoUso,
v.CAT_CATEGORIA as categoria,
v.CAT_DESCR_CATEGORIA as descCategoria,
v.COD_TIPO_USO_CATASTALE as tipoUso,
v.DESCR_TIPO_USO_CATASTALE as descTipoUso
from rsbl_ui_tipo_uso_catastale v</SQLQuery>
            <description/>
        </primitiveView>
```
<img width="806" alt="Schermata 2020-05-27 alle 23 39 40" src="https://user-images.githubusercontent.com/8250758/83075185-b5ccc300-a073-11ea-88a2-74ed48d79192.png">

volevo creare una chiave sul primo campo e una sul secondo, e nel file è stato scritto questo:

  ```
  <key id="kd_1590615562776">
            <projection arg="Tipo_Uso_Catastale_view[0]"/>
            <description/>
        </key>
    <key id="kd_1590615562819">
            <projection arg="Tipo_Uso_Catastale_view[0]"/>
            <description/>
        </key>
```

Modificandolo a mano, mettendo prima Tipo_Uso_Catastale_view[1] e poi Tipo_Uso_Catastale_view[2], l'errore non viene più riportato.

**Comment by roodsey** [comment]
Ho appena ricreato le due chiavi senza problemi: forse l'aggiornamento di Monolith ha risolto il problema?

**Comment by valeriosantarelli** [comment]
Confermo. Mi pare risolto.
